name: Deploy to Google Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  deploy-to-gar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker REGION-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repository/${{ github.sha }} .
          docker push REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repository/${{ github.sha }}
        env:
          REGION: asia-south1  # Replace with your region

      - name: Verify push
        run: gcloud artifacts docker images list --repository=my-repository --location=$REGION
